apiVersion: v1
kind: Pod
metadata:
  labels:
    app: spring-build-ci
spec:
  containers:
    - name: maven
      image: maven:alpine
      volumeMounts:
        - name: m2
          mountPath: /root/.m2/
    - name: docker-tools
      image: rmkanda/docker-tools:latest
      volumeMounts:
        - mountPath: /var/run
          name: docker-sock
        - mountPath: /tmp/trivycache/
          name: trivycache
    - name: trufflehog
      image: rmkanda/trufflehog
    - name: licensefinder
      image: licensefinder/license_finder
  volumes:
    - name: m2
      emptyDir: {}
    - name: docker-sock
      emptyDir: {}
    - name: trivycache
      emptyDir: {}
