apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dso
  name: dso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dso
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dso
    spec:
      containers:
      - image: baladevsecops/dso
        name: dso
        ports:
        - containerPort: 8080
        resources: 
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
status: {}
